name: PHPStan

on:
  push:
    branches:
      - main

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --configuration phpstan.neon --level max
